package udacore.memorysubsystem.spec.modules

import framework.macros.SpecEmit.spec
import framework.specs.Spec._
import udacore.common.spec.DesignRuleSpecs._

import udacore.memorysubsystem.spec.shared.MemorySubsystemBundlesSpecs._
import udacore.memorysubsystem.spec.shared.MemorySubsystemParamsSpecs.paramMemDisambig

/** LoadUnit (ADR-003 M2).
  *
  * Loads execute freely and speculatively; a wrong-path load has no
  * architectural effect and is filtered at PublishMux by epoch. The LSU adds no
  * extra load-speculation gate. Every load probes the StoreBuffer for
  * store-to-load forwarding rather than stalling on an older store.
  */
object LoadUnitSpecs {
  val contLoadUnit = spec {
    CONTRACT("LoadUnit")
      .desc(
        "Load unit issues memory reads, probes the StoreBuffer for forwarding, and forwards responses toward writeback."
      )
      .has(
        intfDispatchIn,
        intfMemoryReqOut,
        intfMemoryRespIn,
        intfLoadFwdQuery,
        intfLoadFwdData
      )
      .build()
  }

  val intfDispatchIn = spec {
    INTERFACE("LoadDispatchIn")
      .desc("Dispatch payload entering the load unit.")
      .uses(bndLoadDispatch)
      .is(rawReadyValidIntf)
      .build()
  }

  val intfMemoryReqOut = spec {
    INTERFACE("LoadMemoryReqOut")
      .desc("Memory request generated by the load unit.")
      .uses(bndLoadMemoryReq)
      .is(rawReadyValidIntf)
      .build()
  }

  val intfMemoryRespIn = spec {
    INTERFACE("LoadMemoryRespIn")
      .desc("Memory response consumed by the load unit.")
      .uses(bndLoadMemoryResp)
      .is(rawReadyValidIntf)
      .build()
  }

  val intfLoadFwdQuery = spec {
    INTERFACE("LoadFwdQueryOut")
      .desc("Store-to-load forwarding probe issued to the StoreBuffer.")
      .uses(bndLoadFwdQuery)
      .is(rawReadyValidIntf)
      .build()
  }

  val intfLoadFwdData = spec {
    INTERFACE("LoadFwdDataIn")
      .desc("Per-byte forwarding result returned from the StoreBuffer.")
      .uses(bndLoadFwdData)
      .is(rawReadyValidIntf)
      .build()
  }

  val funcLoadForward = spec {
    FUNCTION("LoadForward")
      .desc(
        "Every load probes the StoreBuffer via LoadFwdQuery{addr,size,olderThan=seqTag}; a full byte-mask hit is the load result with NO controller read, a partial/no hit issues a read and merges forwarded bytes over the returned line (ADR-003 D-3.9)."
      )
      .uses(intfLoadFwdQuery, intfLoadFwdData)
      .build()
  }

  val funcConservativeDisambig = spec {
    FUNCTION("ConservativeDisambig")
      .desc(
        "With MemDisambig=false (base and N=1) a load MUST NOT issue a controller read past an older store whose address is not yet resolved; it may only forward/bypass past buffered stores with known addresses (ADR-003 D-3.10)."
      )
      .uses(paramMemDisambig)
      .note("At N=1 all older stores have resolved before a load can issue, so this is free.")
      .note(
        "ADR-003 D-3.11 (proposed): the speculative path (MemDisambig=true, issue past an unresolved store with a commit-head memory-order redirect on late match) elaborates away entirely at the false base."
      )
      .build()
  }

  val propLoadNoOrderingGate = spec {
    PROPERTY("LoadNoOrderingGate")
      .desc(
        "The LoadUnit adds no load-speculation ordering gate of its own; a wrong-path load's result is filtered downstream at PublishMux by epoch, not stalled in the LSU (ADR-003 D-3.8)."
      )
      .uses(intfMemoryReqOut)
      .note("Paired with an @LocalSpec design assert that no LSU-internal epoch gate withholds a load's controller read.")
      .build()
  }
}
