package udacore.memorysubsystem.spec.shared

import framework.macros.SpecEmit.spec
import framework.specs.Spec._

object MemorySubsystemBundlesSpecs {
  val bndLoadDispatch = spec {
    BUNDLE("LoadDispatch")
      .desc("Dispatch payload entering the load unit.")
      .note("Fields: uopId, addr, size, sign, meta")
      .build()
  }

  val bndLoadMemoryReq = spec {
    BUNDLE("LoadMemoryReq")
      .desc("Memory request generated by the load unit.")
      .note("Fields: addr, size, id, meta")
      .build()
  }

  val bndLoadMemoryResp = spec {
    BUNDLE("LoadMemoryResp")
      .desc("Memory response consumed by the load unit.")
      .note("Fields: data, id, fault, meta")
      .note(
        "meta carries the txnId reassociation key (ADR-003 D-3.13); responses are UNORDERED and matched by txnId, never by position."
      )
      .build()
  }

  val bndStoreDispatch = spec {
    BUNDLE("StoreDispatch")
      .desc("Dispatch payload entering the store unit.")
      .note("Fields: uopId, addr, size, data, meta")
      .build()
  }

  val bndStoreMemoryReq = spec {
    BUNDLE("StoreMemoryReq")
      .desc("Memory request generated by the store unit.")
      .note("Fields: addr, size, data, id, meta")
      .build()
  }

  val bndStoreMemoryResp = spec {
    BUNDLE("StoreMemoryResp")
      .desc("Memory acknowledgement consumed by the store unit.")
      .note("Fields: id, fault, meta")
      .build()
  }

  val bndControllerReq = spec {
    BUNDLE("ControllerReq")
      .desc("Request packet entering the memory controller.")
      .note("Fields: addr, data, size, cmd, id")
      .build()
  }

  val bndControllerResp = spec {
    BUNDLE("ControllerResp")
      .desc("Response packet leaving the memory controller.")
      .note("Fields: data, id, fault")
      .note(
        "id carries the txnId (loads) reassociation key (ADR-003 D-3.13); the controller enforces no program order and reassociates by tag only."
      )
      .build()
  }

  // ADR-003 M2 / D-3.9: store-to-load forwarding probe from the LoadUnit.
  val bndLoadFwdQuery = spec {
    BUNDLE("LoadFwdQuery")
      .desc("Store-to-load forwarding probe issued by the LoadUnit to the StoreBuffer.")
      .note("Fields: addr, size, olderThan(seqTag)")
      .note(
        "olderThan is the canonical seqTag of the probing load; the buffer forwards only from entries with entry.seqTag < load.seqTag, wrap-aware (ADR-003 D-3.9, ADR-012 D-12.3)."
      )
      .build()
  }

  // ADR-003 M2 / D-3.9: per-byte forwarding result from the StoreBuffer.
  val bndLoadFwdData = spec {
    BUNDLE("LoadFwdData")
      .desc("Per-byte forwarded store bytes plus coverage mask and full-hit flag.")
      .note("Fields: data, mask (per-byte coverage), hit (full-cover flag)")
      .note(
        "Full byte-mask coverage suppresses the controller read entirely; partial/no hit issues a read and merges forwarded bytes over it (ADR-003 D-3.9)."
      )
      .build()
  }

  // ADR-003 M4 / D-3.6: MemoryController write acknowledgement to the StoreBuffer.
  val bndWriteAck = spec {
    BUNDLE("WriteAck")
      .desc("Write acknowledgement from the MemoryController to the StoreBuffer for a drained committed store.")
      .note("Fields: seqTag, fault")
      .note(
        "The StoreBuffer frees the HEAD entry and emits StoreComplete{seqTag, fault} only on this ack; the fault field of StoreComplete is sourced from this ack (ADR-003 D-3.4/D-3.6)."
      )
      .build()
  }

  // ADR-003 M1 / D-3.6: post-ack store retirement/fault token (no data).
  val bndStoreComplete = spec {
    BUNDLE("StoreComplete")
      .desc("Store retirement/fault acknowledgement from the memory subsystem (no data field).")
      .note("Fields: seqTag, fault")
      .note(
        "Emitted after a committed store's write is acked; used for fences and fault reporting. Backend retirement is NOT blocked on this (ADR-003 D-3.6)."
      )
      .build()
  }

  val bndDispatcherLoad = spec {
    BUNDLE("DispatcherLoad")
      .desc("Load request forwarded by the memory dispatcher.")
      .note("Fields: addr, size, id, meta")
      .build()
  }

  val bndDispatcherStore = spec {
    BUNDLE("DispatcherStore")
      .desc("Store request forwarded by the memory dispatcher.")
      .note("Fields: addr, size, data, id, meta")
      .build()
  }

  val bndRespArb = spec {
    BUNDLE("RespArb")
      .desc("Response channel aggregated by the memory subsystem arbiter.")
      .note("Fields: data, id, source, fault")
      .note(
        "id carries txnId for loads and seqTag for StoreComplete; responses are UNORDERED to the backend and reassociated by tag (ADR-003 D-3.13, M4)."
      )
      .build()
  }
}
