name: Scala CI

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.scala'
      - '**/*.sbt'
      - '.scalafmt.conf'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.scala'
      - '**/*.sbt'
      - '.scalafmt.conf'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests
      run: sbt clean assembly test
